package com.sharemyoffice.dao.entities;

// Generated Jun 27, 2015 4:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CityMaster generated by hbm2java
 */
@Entity
@Table(name = "city_master", catalog = "sharemyoffice")
public class CityMaster implements java.io.Serializable {

	private Integer id;
	private String name;
	private String state;
	private String country;
	private Set<OfficeInfo> officeInfos = new HashSet<OfficeInfo>();

	public CityMaster() {
	}

	public CityMaster(String name, String state, String country) {
		this.name = name;
		this.state = state;
		this.country = country;
	}

	public CityMaster(String name, String state, String country, Set<OfficeInfo> officeInfos) {
		this.name = name;
		this.state = state;
		this.country = country;
		this.officeInfos = officeInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 10)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cityMaster")
	public Set<OfficeInfo> getOfficeInfos() {
		return this.officeInfos;
	}

	public void setOfficeInfos(Set<OfficeInfo> officeInfos) {
		this.officeInfos = officeInfos;
	}

}
