package com.sharemyoffice.dao.entities;

// Generated Jun 27, 2015 4:31:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OfficeImages generated by hbm2java
 */
@Entity
@Table(name = "office_images", catalog = "sharemyoffice")
public class OfficeImages implements java.io.Serializable {

	private Integer id;
	private OfficeInfo officeInfo;
	private String images;

	public OfficeImages() {
	}

	public OfficeImages(OfficeInfo officeInfo, String images) {
		this.officeInfo = officeInfo;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "office_info_id", nullable = false)
	public OfficeInfo getOfficeInfo() {
		return this.officeInfo;
	}

	public void setOfficeInfo(OfficeInfo officeInfo) {
		this.officeInfo = officeInfo;
	}

	@Column(name = "images", nullable = false)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

}
