package com.sharemyoffice.dao.entities;

// Generated Jun 27, 2015 4:31:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OfficeFacilities generated by hbm2java
 */
@Entity
@Table(name = "office_facilities", catalog = "sharemyoffice")
public class OfficeFacilities implements java.io.Serializable {

	private Integer id;
	private OfficeInfo officeInfo;
	private AvailableFacilitiesMaster availableFacilitiesMaster;

	public OfficeFacilities() {
	}

	public OfficeFacilities(OfficeInfo officeInfo,
			AvailableFacilitiesMaster availableFacilitiesMaster) {
		this.officeInfo = officeInfo;
		this.availableFacilitiesMaster = availableFacilitiesMaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "office_info_id", nullable = false)
	public OfficeInfo getOfficeInfo() {
		return this.officeInfo;
	}

	public void setOfficeInfo(OfficeInfo officeInfo) {
		this.officeInfo = officeInfo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "available_facilities_id", nullable = false)
	public AvailableFacilitiesMaster getAvailableFacilitiesMaster() {
		return this.availableFacilitiesMaster;
	}

	public void setAvailableFacilitiesMaster(
			AvailableFacilitiesMaster availableFacilitiesMaster) {
		this.availableFacilitiesMaster = availableFacilitiesMaster;
	}

}
