package com.sharemyoffice.dao.entities;
// Generated Jun 27, 2015 4:31:39 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OfficeInfo generated by hbm2java
 */
@Entity
@Table(name="office_info"
    ,catalog="sharemyoffice"
)
public class OfficeInfo  implements java.io.Serializable {


     private Integer id;
     private User user;
     private CityMaster cityMaster;
     private String officeName;
     private String officeAddress;
     private int officePincode;
     private String description;
     private Integer cost;
     private String squareFeet;
     private String distanceFromBusStand;
     private String officeTiming;
     private int imagesCount;
     private String officeWebsite;
     private Set<OfficeImages> officeImageses = new HashSet<OfficeImages>();
     private Set<OfficeFacilities> officeFacilitieses = new HashSet<OfficeFacilities>();

    public OfficeInfo() {
    }

	
    public OfficeInfo(User user, CityMaster cityMaster, String officeName, String officeAddress, int officePincode, String description, String distanceFromBusStand, int imagesCount) {
        this.user = user;
        this.cityMaster = cityMaster;
        this.officeName = officeName;
        this.officeAddress = officeAddress;
        this.officePincode = officePincode;
        this.description = description;
        this.distanceFromBusStand = distanceFromBusStand;
        this.imagesCount = imagesCount;
    }
    public OfficeInfo(User user, CityMaster cityMaster, String officeName, String officeAddress, int officePincode, String description, Integer cost, String squareFeet, String distanceFromBusStand, String officeTiming, int imagesCount, String officeWebsite, Set<OfficeImages> officeImageses, Set<OfficeFacilities> officeFacilitieses) {
       this.user = user;
       this.cityMaster = cityMaster;
       this.officeName = officeName;
       this.officeAddress = officeAddress;
       this.officePincode = officePincode;
       this.description = description;
       this.cost = cost;
       this.squareFeet = squareFeet;
       this.distanceFromBusStand = distanceFromBusStand;
       this.officeTiming = officeTiming;
       this.imagesCount = imagesCount;
       this.officeWebsite = officeWebsite;
       this.officeImageses = officeImageses;
       this.officeFacilitieses = officeFacilitieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="city_master_id", nullable=false)
    public CityMaster getCityMaster() {
        return this.cityMaster;
    }
    
    public void setCityMaster(CityMaster cityMaster) {
        this.cityMaster = cityMaster;
    }

    
    @Column(name="office_name", nullable=false)
    public String getOfficeName() {
        return this.officeName;
    }
    
    public void setOfficeName(String officeName) {
        this.officeName = officeName;
    }

    
    @Column(name="office_address", nullable=false)
    public String getOfficeAddress() {
        return this.officeAddress;
    }
    
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    
    @Column(name="office_pincode", nullable=false)
    public int getOfficePincode() {
        return this.officePincode;
    }
    
    public void setOfficePincode(int officePincode) {
        this.officePincode = officePincode;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="cost")
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    
    @Column(name="square_feet/seat", length=50)
    public String getSquareFeet() {
        return this.squareFeet;
    }
    
    public void setSquareFeet(String squareFeet) {
        this.squareFeet = squareFeet;
    }

    
    @Column(name="distance_from_bus_stand", nullable=false)
    public String getDistanceFromBusStand() {
        return this.distanceFromBusStand;
    }
    
    public void setDistanceFromBusStand(String distanceFromBusStand) {
        this.distanceFromBusStand = distanceFromBusStand;
    }

    
    @Column(name="office_timing", length=50)
    public String getOfficeTiming() {
        return this.officeTiming;
    }
    
    public void setOfficeTiming(String officeTiming) {
        this.officeTiming = officeTiming;
    }

    
    @Column(name="images_count", nullable=false)
    public int getImagesCount() {
        return this.imagesCount;
    }
    
    public void setImagesCount(int imagesCount) {
        this.imagesCount = imagesCount;
    }

    
    @Column(name="office_website", length=50)
    public String getOfficeWebsite() {
        return this.officeWebsite;
    }
    
    public void setOfficeWebsite(String officeWebsite) {
        this.officeWebsite = officeWebsite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="officeInfo")
    public Set<OfficeImages> getOfficeImageses() {
        return this.officeImageses;
    }
    
    public void setOfficeImageses(Set<OfficeImages> officeImageses) {
        this.officeImageses = officeImageses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="officeInfo")
    public Set<OfficeFacilities> getOfficeFacilitieses() {
        return this.officeFacilitieses;
    }
    
    public void setOfficeFacilitieses(Set<OfficeFacilities> officeFacilitieses) {
        this.officeFacilitieses = officeFacilitieses;
    }




}


